# Site settings
title: PipeRift
description: 'PipeRift - A small game development studio.'
url: 'http://piperift.com'
baseurl: '/'
google_analytics: 'UA-27762240-2'
#disqus_shortname: 'piperift'

author:
  name: 'PipeRift'
  email: info@piperift.com
  twitter_username: piperift
  github_username:  PipeRift

team:
  -
    name: 'Miguel Fernández Arce'
    position: 'Creative Director'
    twitter: muitxer
    github: muit
    linkedin: muitxer
    email: muit@piperift.com
  - 
    name: 'Guillermo Castilla Mejías'
    position: 'Designer'
    email: gcastillam@piperift.com
  -
    name: 'Miguel Coronado García'
    position: '3D Artist'
  - 
    name: 'Martin Barbudo'
    position: 'Concept Artist'
    twitter: MartinBarbudo
  - 
    name: 'Antonio Serón Molina'
    position: 'Additional Design'
    email: antonioseronmolina@gmail.com


defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']


excerpt_separator: '<!--end-preview-->'
