url: https://piperift.com

# Site settings
title: PipeRift
description: 'An small game development studio.'
url: 'https://piperift.com'
google_analytics: 'UA-27762240-2'
#disqus_shortname: 'piperift'

author:
  name: 'PipeRift'
  email: info@piperift.com

# Team names, titles and social links
people:
- name: Miguel Fernández
  position: Founder & programmer
  social:
    - title: twitter
      url: https://twitter.com/muitxer
    - title: linkedin
      url: https://www.linkedin.com/in/muitxer
    - title: github
      url: https://github.com/muit
    - title: envelope
      url: mailto:muit@piperift.com

- name: Miguel Coronado García
  position: 3D Artist
  social:
    - title: envelope
      url: mailto:migueldel89@gmail.com

- name: Guillermo Castilla Mejías
  position: Narrative Designer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/guillermo-castilla-mejias-8b3246b3
    - title: envelope
      url: mailto:guillecastillam@gmail.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/piperift
  - title: itch-io
    url: https://piperift.itch.io
  - title: github
    url: http://github.com/piperift

# Postal address (add as many lines as necessary)
address:
  - line: Tres Cantos, Madrid, 28760


# Build settings
permalink: /:year/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate', 'kramdown']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'LICENSE',]
excerpt_separator: '<!--end-preview-->'

permalink: pretty

# Pagination
paginate: 3
paginate_path: "/page/:num/"
