# Site settings
title: PipeRift
description: 'PipeRift - A small game development studio.'
url: 'http://piperift.com'
baseurl: '/'
google_analytics: 'UA-27762240-2'
#disqus_shortname: 'piperift'

author:
  name: 'PipeRift'
  email: info@piperift.com
  twitter_username: piperift
  github_username:  PipeRift

team:
  -
    name: 'Muit '
    position: 'Creative Director'
    twitter: muitxer
    github: muit
    linkedin: muitxer
    email: miguel_3c@hotmail.com
  -
    name: 'Miguel Coronado'
    position: '3D Artist'
  - 
    name: 'Antonio Serón'
    position: 'Designer & Scriptwriter'
    email: antonioseronmolina@gmail.com
  - 
    name: 'Isabel Royán'
    position: 'Composer & Sound Designer'
    email: i.royan@hotmail.com


defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'
  -
    scope:
      path: "presskit"
      type: "pages"
    values:
      layout: "presskit"

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']


excerpt_separator: '<!--end-preview-->'
